# Site settings
title: "杨恺简历"
description: "Jekyll简历, 托管于GitHub"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "杨恺"
resume_title:                   "测试开发工程师"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "yk_ecust_2007@163.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "17717849332"
resume_contact_address:         "上海市浦东新区塘桥宁阳小区12弄2号604室"

resume_header_contact_info:     "陆金所 • 177-1784-9332 • yk_ecust_2007@163.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>专注python web开发, 擅长性能测试, 自动化测试, 自动化爬虫, 课余时间也在从事机器学习和深度学习的探索</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/miniyk2012"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/%E6%81%BA-%E6%9D%A8-0101b6aa/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
  resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
